### ISSUE TITLE
Deep link delegation for swift broken in xcode 7 / swift 2

### ISSUE THREAD

**Issue by jmatheson** [hokolinks/hoko-docs#1]
Your sample code does not work in xcode7, any update?

**Comment by ivanbruel** [comment]
The only problem I'm seeing is that the annotation parameter is no longer an optional AnyObject:

``` swift
func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject) -> Bool {
  return Hoko.deeplinking().openURL(url, sourceApplication: sourceApplication, annotation: annotation)
}
```

Might it be due to the fact that any route mapped by Hoko automatically gets handled by Hoko and doesn't go through the `application:openURL:sourceApplication:annotation:` call?

**Comment by jmatheson** [comment]
Yes, that sounds correct. I got it fixed on my end yesterday. It was the optional coupled with another unrelated issue in my source code. Thx!
