### ISSUE TITLE
Typo in link to setting up a custom domain

### ISSUE THREAD

**Issue by jmatheson** [hokolinks/hoko-docs#2]
If you wish to use your own domain(s) on your HOKO smart links (see “Setting up a custom domain”)

The link should read:
http://support.hokolinks.com/how-to-setup-a-custom-domain/
instead of 
http://support.hokolinks.com/how-tp-setup-a-custom-domain/

**Comment by jmatheson** [comment]
also your sample code below that (both C and Swift) shows customDomains with an S. Looks like it is just customDomain and possibly not an array.

**Comment by hugocore** [comment]
Thank you for the heads-up @jmatheson
